### ISSUE TITLE
Should CKAN tracking be enabled?

### ISSUE THREAD

**Issue by heinlja** [datagovuk/ckanext-ga-report#5]
May sound as a stupid question, but does this extension require "ckan.tracking_enabled" to be set to True in the configuration? Looks like no analytics JavaScript is added to the pages otherwise.

**Comment by heinlja** [comment]
Actually, this might sound even more stupid, but I'm starting to get the feeling that in order for the ckanext-ga-report to function properly, it requires ckanext-googleanalytics to be installed and enabled as well. Is that true?

**Comment by davidread** [comment]
No, you just need to add the GA snippet in your config. For example we have:
```
ckan.template_footer_end =   <script type="text/javascript">
 <!--//--><![CDATA[//><!--
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-10855508-1', 'auto');
 ga('send', 'pageview');
 //--><!]]>
 </script>
```
We don't use ckan.tracking_enabled or ckanext-googleanalytics.
