### ISSUE TITLE
No graphs being displayed

### ISSUE THREAD

**Issue by heinlja** [datagovuk/ckanext-ga-report#6]
I get no graphs displayed when going to site usage by browsers (data/site-usage?month=#browsers_names), by operating systems, etc.

Apparently the "c.browsers_graph" that is being passed to rickshaw_graph(...) in ckanext/ga_report/templates/ga_report/site/index.html  is empty:
```sh
${rickshaw_graph(c.browsers_graph,'browsers',mode='stack')}
```

The totals page (/data/site-usage?month=#totals) is working though.
Any ideas on what could be wrong?

**Comment by heinlja** [comment]
Not sure what I did, but now the graphs are "almost" being displayed, meaning an empty grid is displayed without any lines drawn on it (see attached screenshot). At the same time, the graph legend displays correctly. Any ideas where the problem might be?
![empty_graph](https://cloud.githubusercontent.com/assets/1263247/6019556/83ed0a2a-abaa-11e4-8030-0508effc3d95.jpg)

**Comment by heinlja** [comment]
Any ideas on this issue? The problem is still the same: the graph grid is displayed, but no graph displayed. Is it a Google Analytics issue, or should I look somewhere in the code?

**Comment by davidread** [comment]
It suggests you have no data. You could look in the database by running 'psql ckan'. If you run this sql you should see rows like this:
```
ckan=# select * from ga_stat where stat_name='Browsers';

                  id                  | period_name | stat_name |           key            | value  | period_complete_day
--------------------------------------+-------------+-----------+--------------------------+--------+---------------------
 22dc453a-49e2-43e5-8d4e-fbcd86b528bb | 2012-07     | Browsers  | Chrome                   | 100729 | 31
 ba79ff9c-06ec-4e95-b14f-38bec73ed812 | 2012-07     | Browsers  | Mozilla Compatible Agent | 2141   | 31
```

The code that gets this out of the database is here:

https://github.com/datagovuk/ckanext-ga-report/blob/master/ckanext/ga_report/controller.py#L170

**Comment by heinlja** [comment]
Sorry, I forgot to say that the data is there. It is correctly received from GA and stored in the database, as you have indicated in your SQL query. It's just that the graph is not displayed. The grid is drawn, but not the data lines on it. From inspecting the code, I'm not sure if the graph is somehow queried as an image from GA or is it drawn by some local code or JS library?

**Comment by davidread** [comment]
Ah good, so if the database has the data, but c.browsers_graph is empty, then you need to check where it fails in the controller:

https://github.com/datagovuk/ckanext-ga-report/blob/master/ckanext/ga_report/controller.py#L170-L243

That code just rejigs the data into the format required to display.

Yes it's displayed using the Rickshaw JS library.

**Comment by heinlja** [comment]
The problem was a lot more prosaic. There was simply not enough data to draw the graph :) The period was monthly and I had only one month's data. Generating some arbitrary data for another month created the graph. So it's case closed.
