### ISSUE TITLE
can't generate token.dat file from credentials.json

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/ckanext-ga-report#8]
Hi,

when i try to create token.dat file running 

***"paster getauthtoken credentials.jason --config=/var/ckan/ckan.ini"*** command

i get:

***"You must provide no more than 0 arguments"***

This is credentials.json

{
        "web":{
                "auth_uri":"https://accounts.google.com/o/oauth2/auth",
                "client_secret":"*********************************",
                "token_uri":"https://accounts.google.com/o/oauth2/token",
                "client_email":"9*******************-*************************@developer.gserviceaccount.com",
                "client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/**************-******************************@developer.gserviceaccount.com",
                "client_id":"*********************-****************************************************.com",
                "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs"
                }
}

Can anyone suggest me what to do?

Thank you.

**Comment by davidread** [comment]
The parameter you added to the paster command "credentials.jason" is not being accepted. Try increasing the max_args to 1 here:

https://github.com/datagovuk/ckanext-ga-report/blob/master/ckanext/ga_report/command.py#L44

If this works, could you update the README too and do a pull request?

**Comment by tbalaz** [comment]
Hi David,

i made a typo it's not credentials.***jason*** but credentials.***json*** in parameter.

After changing "max_args = 1" i get "Can't find the credentials file".

I've tried to change ownership on credentials.json to co:www-data but id does not help.

**Comment by davidread** [comment]
@tbalaz That error message is misleading I'm afraid. I've changed the ckanext-ga-report code so that it gives the real error now.

It looks like you created a client ID for a 'web app' rather than an 'installed app'. So do go through that again.

I've much improved the instructions now:

https://github.com/datagovuk/ckanext-ga-report/commit/28ccc4f520456a98e799d0b1b457f1efb312d5a8

**Comment by tbalaz** [comment]
@davidread 

I'm not clear on instructions since i work only in terminal.

I have created credentials.json for type:installed app.

Then i used client_id from .json and inserted it in https request like this:

https: //accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=**this is where i have inserted my client_id**.apps.googleusercontent.com&access_type=offline

Then i have been redirected to 

http://localhost:8080/?code=4/S0m3num83r5-&s0m3lett3rsrhjwkjsduofyzj0.g8f93jd889sjsj29d-Iw93

When i run curl http://localhost:8080/?code=4/S0m3num83r5-&s0m3lett3rsrhjwkjsduofyzj0.g8f93jd889sjsj29d-Iw93

nothing happens.

when i run paster getauthtoken --config=/var/ckan/ckan.ini i get:

![getauth](https://cloud.githubusercontent.com/assets/8652002/6464637/ddf1edde-c1bb-11e4-9b08-4b49a26c5474.PNG)

If i login, site redirects me back to 

https: //accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=**this is where i have inserted my client_id**.apps.googleusercontent.com&access_type=offline

![accept](https://cloud.githubusercontent.com/assets/8652002/6464851/6b1c31b4-c1bd-11e4-832e-bd0aa23667a5.PNG)


If i accept then i get 

![nojava](https://cloud.githubusercontent.com/assets/8652002/6464897/af7e855a-c1bd-11e4-9278-448dd134d2cb.PNG)

Please advice

**Comment by davidread** [comment]
The paster command launches the URL (your command-line browser) and then listens on port 8080 for that curl request. So quit your browser (it is no good without javascript) and paster should be left still running. Then run curl in another terminal of the same machine.

Otherwise, try uninstalling your browser. Paster should just print the URL on the screen that you can copy/paste into your local desktop browser, which runs javascript.

Let me know how it goes.

**Comment by tbalaz** [comment]
@davidread 

in **terminal session 1** i have started paster command which starts browser in terminal window.

Then i have opened new **terminal session 2** with same user and run curl,

curl hangs and nothing happens.

If i do ctrl+c in **terminal session 1** to quit browser in terminal window i get 

(ckan)co@data-web:/src/ckan$ curl http://localhost:8080/?code=4/P-Y8ZPGVVwqrUEOYMVXaN25EU0T2rT4IKYWOQoGVMLY.IqhPGDb8nKwXYFZr95uygvX30OC_lwI
curl: (56) Recv failure: Connection reset by peer

Please advice.

**Comment by tbalaz** [comment]
@davidread 

update on this issue. I have uninstalled links and elinks.

now when i start paster command in **terminal session 1** i get:

***(ckan)co@data-web:/src/ckanext-ga-report$ paster --plugin=ckanext-ga-report getauthtoken --config=/var/ckan/ckan.ini
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=123456781234-crt6blabla1swfgarg3raege637323fc8.apps.googleusercontent.com&access_type=offline

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver***

Now when i start curl in **terminal session 2** i get:

Authentication has failed: invalid_grant

I will try to do this with new client ID.

**Comment by tbalaz** [comment]
@davidread 

After creating new client id i have maneged to create token.dat running curl in new terminal session.

i have tried to run ***paster loadanalytics latest --config=/var/ckan/ckan.ini***

command returns:

Traceback (most recent call last):
  File "/home/co/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/vagrant/src/ckanext-ga-report/ckanext/ga_report/command.py", line 140, in command
    downloader = DownloadAnalytics(svc, self.token, profile_id=get_profile_id(svc),
  File "/vagrant/src/ckanext-ga-report/ckanext/ga_report/ga_auth.py", line 65, in get_profile_id
    webproperties = service.management().webproperties().list(accountId=accountId).execute()
UnboundLocalError: local variable 'accountId' referenced before assignment


Any suggestions?

**Comment by tbalaz** [comment]
Update on this issue:
Hi,

I have installed latest ckanext-ga-report.

When i run **paster loadanalytics latest --config=.../ckan.ini** i'm getting error 

2015-03-05 13:45:36,006 ERROR [ckanext.ga_report.ga_auth] The specified GA account is not available. Configure googleanalytics.account to one of: [u'Portal otvorenih podataka RH']

In ckan.ini i have

**googleanalytics.account = 'Portal otvorenih podataka HR'**

Any suggestions what to do?

**Comment by tbalaz** [comment]
@davidread 

solved.

Everything works now. 

i had typo ckan.ini **googleanalyitics.account=account name** parameter.

Figured this out after installing latest ga-reports.

The specified GA account is not available. Configure googleanalytics.account to one of: [u'My account name']

Error explained everything.

Thanks David

**Comment by davidread** [comment]
Great, cheers
